export type LOAD_INTIATION_TYPE = 'DOCS/LOAD_INTIATION';
export const LOAD_INTIATION: LOAD_INTIATION_TYPE = 'DOCS/LOAD_INTIATION';

export type LOAD_SUCCESS_TYPE = 'DOCS/LOAD_SUCCESS';
export const LOAD_SUCCESS: LOAD_SUCCESS_TYPE = 'DOCS/LOAD_SUCCESS';

export type LOAD_FAILURE_TYPE = 'DOCS/LOAD_FAILURE';
export const LOAD_FAILURE: LOAD_FAILURE_TYPE = 'DOCS/LOAD_FAILURE';

export type LOAD_CANCEL_TYPE = 'DOCS/LOAD_CANCEL';
export const LOAD_CANCEL: LOAD_CANCEL_TYPE = 'DOCS/LOAD_CANCEL';

export type DEFAULT_ACTION_TYPE = '';
export const DEFAULT_ACTION_TYPE: DEFAULT_ACTION_TYPE = '';
