export type LOAD_INITIATION_TYPE = 'DOCS/LOAD_INITIATION';
export const LOAD_INITIATION: LOAD_INITIATION_TYPE = 'DOCS/LOAD_INITIATION';

export type LOAD_SUCCESS_TYPE = 'DOCS/LOAD_SUCCESS';
export const LOAD_SUCCESS: LOAD_SUCCESS_TYPE = 'DOCS/LOAD_SUCCESS';

export type LOAD_FAILURE_TYPE = 'DOCS/LOAD_FAILURE';
export const LOAD_FAILURE: LOAD_FAILURE_TYPE = 'DOCS/LOAD_FAILURE';

export type LOAD_CANCEL_TYPE = 'DOCS/LOAD_CANCEL';
export const LOAD_CANCEL: LOAD_CANCEL_TYPE = 'DOCS/LOAD_CANCEL';

export type CLEAR_ERROR_TYPE = 'DOCS/CLEAR_ERROR';
export const CLEAR_ERROR: CLEAR_ERROR_TYPE = 'DOCS/CLEAR_ERROR';
