export type LOAD_DATA_INITIATION_TYPE = 'FOOBAR/LOAD_DATA_INITIATION';
export type LOAD_DATA_SUCCESS_TYPE = 'FOOBAR/LOAD_DATA_SUCCESS';
export type LOAD_DATA_FAILURE_TYPE = 'FOOBAR/LOAD_DATA_FAILURE';
export const LOAD_DATA_INITIATION: LOAD_DATA_INITIATION_TYPE = 'FOOBAR/LOAD_DATA_INITIATION';
export const LOAD_DATA_SUCCESS: LOAD_DATA_SUCCESS_TYPE = 'FOOBAR/LOAD_DATA_SUCCESS';
export const LOAD_DATA_FAILURE: LOAD_DATA_FAILURE_TYPE = 'FOOBAR/LOAD_DATA_FAILURE';
