type LOAD_INTIATION_TYPE = 'DOCS/LOAD_INTIATION';
export const LOAD_INTIATION: LOAD_INTIATION_TYPE = 'DOCS/LOAD_INTIATION';
type LOAD_SUCCESS_TYPE = 'DOCS/LOAD_SUCCESS';
export const LOAD_SUCCESS: LOAD_SUCCESS_TYPE = 'DOCS/LOAD_SUCCESS';
type LOAD_FAILURE_TYPE = 'DOCS/LOAD_FAILURE';
export const LOAD_FAILURE: LOAD_FAILURE_TYPE = 'DOCS/LOAD_FAILURE';
