export type ADD_TODO_TYPE = 'TODO_APP/ADD_TODO';
export const ADD_TODO: ADD_TODO_TYPE = 'TODO_APP/ADD_TODO';

export type INPUT_TYPE = 'TODO_APP/INPUT';
export const INPUT: INPUT_TYPE = 'TODO_APP/INPUT';

export type DELETE_TODO_TYPE = 'TODO_APP/DELETE_TODO';
export const DELETE_TODO: DELETE_TODO_TYPE = 'TODO_APP/DELETE_TODO';
