export interface ThemeColorMap {
  dark1: string,
  dark2: string,
  dark3: string,
  light1: string,
  light2: string,
  light3: string,
  primary: string,
  secondary: string,
  ok: string,
  warning: string,
  error: string,
  white1: string,
  white2: string,
  white3: string,
  offwhite: string,
  black1: string,
  black2: string,
  black3: string,
}
